// flow-typed signature: 1dcdd8fc85a527dbf75a60120a4ddb5f
// flow-typed version: <<STUB>>/@svgr/webpack_v4.3.2/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/webpack/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/webpack/lib/index' {
  declare module.exports: $Exports<'@svgr/webpack/lib'>;
}
declare module '@svgr/webpack/lib/index.js' {
  declare module.exports: $Exports<'@svgr/webpack/lib'>;
}
